"use strict";
let latynRule_2 = {
	name:"latynRule_2",

				// rule1:{
				// 	reg:/(?!^)/g,
				// 	translateRule:"A"
				// },
				// rule2:{
				// 	reg:/(?!^)/g,
				// 	translateRule:"A"
				// },
	
	Letter_A:{
				reg:/А/g,
				translateRule:"A"
			},
	Letter_a:{
				reg:/а/g,
				translateRule:"a"
			},
	Letter_B:{
				reg:/Б/g,
				translateRule:"B"
			},
	Letter_b:{
				reg:/б/g,
				translateRule:"b"
			},
	Letter_V:{
				reg:/В/g,
				translateRule:"V"
			},
	Letter_v:{
				reg:/в/g,
				translateRule:"v"
			},
	Letter_H:{
				reg:/Г/g,
				translateRule:"H"
			},
	Letter_h:{
				reg:/г/g,
				translateRule:"h"
			},
	Letter_G:{
				reg:/Ґ/g,
				translateRule:"G"
			},
	Letter_g:{
				reg:/ґ/g,
				translateRule:"g"
			},
	Letter_D:{
				rule1:{
					reg:/^Дя/g,
					translateRule:"Ďa"
				},
				rule2:{
					reg:/^Дь/g,
					translateRule:"Ď"
				},
				rule3:{
					reg:/^Дє/g,
					translateRule:"Ďe"
				},
				rule4:{
					reg:/^Дю/g,
					translateRule:"Ďu"
				},
				rule5:{
					reg:/Д/g,
					translateRule:"D"
				}
			},
	Letter_d:{
				rule1:{
					reg:/дя/g,
					translateRule:"ďa"
				},
				rule2:{
					reg:/дь/g,
					translateRule:"ď"
				},
				rule3:{
					reg:/дє/g,
					translateRule:"ďe"
				},
				rule4:{
					reg:/дю/g,
					translateRule:"ďu"
				},
				rule5:{
					reg:/д/g,
					translateRule:"d"
				}
			},
	Letter_E:{
				reg:/Е/g,
				translateRule:"E"
			},
	Letter_e:{
				reg:/е/g,
				translateRule:"e"
			},
	Letter_Je:{
				reg:/Є/g,
				translateRule:"Je"
			},
	Letter_je:{
				reg:/є/g,
				translateRule:"je"
			},
	Letter_Zh:{
				reg:/Ж/g,
				translateRule:"Ž"
			},
	Letter_zh:{
				reg:/ж/g,
				translateRule:"ž"
			},
	Letter_Z:{
				rule1:{
					reg:/^Зя/g,
					translateRule:"Źa"
				},
				rule2:{
					reg:/^Зь/g,
					translateRule:"Ź"
				},
				rule3:{
					reg:/^Зє/g,
					translateRule:"Źe"
				},
				rule4:{
					reg:/^Зю/g,
					translateRule:"Źu"
				},
				rule5:{
					reg:/З/g,
					translateRule:"Z"
				}
			},
	Letter_z:{
				rule1:{
					reg:/зя/g,
					translateRule:"źa"
				},
				rule2:{
					reg:/зь/g,
					translateRule:"ź"
				},
				rule3:{
					reg:/зє/g,
					translateRule:"źe"
				},
				rule4:{
					reg:/зю/g,
					translateRule:"źu"
				},
				rule5:{
					reg:/з/g,
					translateRule:"z"
				}
			},
	Letter_Y:{
				reg:/И/g,
				translateRule:"Y"
			},
	Letter_y:{
				reg:/и/g,
				translateRule:"y"
			},
	Letter_I:{
				reg:/І/g,
				translateRule:"I"
			},
	Letter_i:{
				reg:/і/g,
				translateRule:"i"
			},
	Letter_Yi:{
				reg:/Ї/g,
				translateRule:"Yi"
			},
	Letter_yi:{
				reg:/ї/g,
				translateRule:"yi"
			},
	Letter_J:{
				reg:/Й/g,
				translateRule:"J"
			},
	Letter_j:{
				reg:/й/g,
				translateRule:"j"
			},
	Letter_K:{
				reg:/К/g,
				translateRule:"K"
			},
	Letter_k:{
				reg:/к/g,
				translateRule:"k"
			},
	Letter_L:{
				rule1:{
					reg:/Л/g,
					translateRule:"L"
				},
				rule2:{
					reg:/^Ль/g,
					translateRule:"Ń"
				},
				rule3:{
					reg:/^Лє/g,
					translateRule:"Ńe"
				},
				rule4:{
					reg:/^Лю/g,
					translateRule:"Ńu"
				},
				rule5:{
					reg:/^Ля/g,
					translateRule:"Ńa"
				}
			},
	Letter_l:{
				rule1:{
					reg:/л/g,
					translateRule:"l"
				},
				rule2:{
					reg:/ль/g,
					translateRule:"ń"
				},
				rule3:{
					reg:/лє/g,
					translateRule:"ńe"
				},
				rule4:{
					reg:/лю/g,
					translateRule:"ńu"
				},
				rule5:{
					reg:/ля/g,
					translateRule:"ńa"
				}
			},
	Letter_M:{
				reg:/М/g,
				translateRule:"M"
			},
	Letter_m:{
				reg:/м/g,
				translateRule:"m"
			},
	Letter_N:{
				rule1:{
					reg:/Н/g,
					translateRule:"N"
				},
				rule2:{
					reg:/^Нь/g,
					translateRule:"Ń"
				},
				rule3:{
					reg:/^Нє/g,
					translateRule:"Ńe"
				},
				rule4:{
					reg:/^Ню/g,
					translateRule:"Ńu"
				},
				rule5:{
					reg:/^Ня/g,
					translateRule:"Ńa"
				}
			},
	Letter_n:{
				rule1:{
					reg:/н/g,
					translateRule:"n"
				},
				rule2:{
					reg:/нь/g,
					translateRule:"ń"
				},
				rule3:{
					reg:/нє/g,
					translateRule:"ńe"
				},
				rule4:{
					reg:/ню/g,
					translateRule:"ńu"
				},
				rule5:{
					reg:/ня/g,
					translateRule:"ńa"
				}
			},
	Letter_O:{
				reg:/О/g,
				translateRule:"O"
			},
	Letter_o:{
				reg:/о/g,
				translateRule:"o"
			},
	Letter_P:{
				reg:/П/g,
				translateRule:"P"
			},
	Letter_p:{
				reg:/п/g,
				translateRule:"p"
			},
	Letter_R:{
				rule1:{
					reg:/Р/g,
					translateRule:"R"
				},
				rule2:{
					reg:/^Рь/g,
					translateRule:"Ŕ"
				},
				rule3:{
					reg:/^Рє/g,
					translateRule:"Ŕe"
				},
				rule4:{
					reg:/^Рю/g,
					translateRule:"Ŕu"
				},
				rule5:{
					reg:/^Ря/g,
					translateRule:"Ŕa"
				}
			},
	Letter_r:{
				rule1:{
					reg:/р/g,
					translateRule:"r"
				},
				rule2:{
					reg:/рь/g,
					translateRule:"ŕ"
				},
				rule3:{
					reg:/рє/g,
					translateRule:"ŕe"
				},
				rule4:{
					reg:/рю/g,
					translateRule:"ŕu"
				},
				rule5:{
					reg:/ря/g,
					translateRule:"ŕa"
				}
			},
	Letter_S:{
				rule1:{
					reg:/С/g,
					translateRule:"S"
				},
				rule2:{
					reg:/^Сь/g,
					translateRule:"Ś"
				},
				rule3:{
					reg:/^Сє/g,
					translateRule:"Śe"
				},
				rule4:{
					reg:/^Сю/g,
					translateRule:"Śu"
				},
				rule5:{
					reg:/^Ся/g,
					translateRule:"Śa"
				}
			},
	Letter_s:{
				rule1:{
					reg:/с/g,
					translateRule:"s"
				},
				rule2:{
					reg:/сь/g,
					translateRule:"ś"
				},
				rule3:{
					reg:/сє/g,
					translateRule:"śe"
				},
				rule4:{
					reg:/сю/g,
					translateRule:"śu"
				},
				rule5:{
					reg:/ся/g,
					translateRule:"śa"
				}
			},
	Letter_T:{
				rule1:{
					reg:/Т/g,
					translateRule:"T"
				},
				rule2:{
					reg:/^Ть/g,
					translateRule:"Ť"
				},
				rule3:{
					reg:/^Тє/g,
					translateRule:"Ťe"
				},
				rule4:{
					reg:/^Тю/g,
					translateRule:"Ťu"
				},
				rule5:{
					reg:/^Тя/g,
					translateRule:"Ťa"
				}
			},
	Letter_t:{
				rule1:{
					reg:/т/g,
					translateRule:"t"
				},
				rule2:{
					reg:/ть/g,
					translateRule:"ť"
				},
				rule3:{
					reg:/тє/g,
					translateRule:"ťe"
				},
				rule4:{
					reg:/тю/g,
					translateRule:"ťu"
				},
				rule5:{
					reg:/тя/g,
					translateRule:"ťa"
				}
			},
	Letter_U:{
				reg:/У/g,
				translateRule:"U"
			},
	Letter_u:{
				reg:/у/g,
				translateRule:"u"
			}, 
	Letter_F:{
				reg:/Ф/g,
				translateRule:"F"
			},
	Letter_f:{
				reg:/ф/g,
				translateRule:"f"
			},
	Letter_Kh:{
				reg:/Х/g,
				translateRule:"X"
			},
	Letter_kh:{
				reg:/х/g,
				translateRule:"x"
			},
	Letter_Ts:{
				rule1:{
					reg:/Ц/g,
					translateRule:"C"
				},
				rule2:{
					reg:/^Ць/g,
					translateRule:"Ć"
				},
				rule3:{
					reg:/^Цє/g,
					translateRule:"Će"
				},
				rule4:{
					reg:/^Цю/g,
					translateRule:"Ću"
				},
				rule5:{
					reg:/^Ця/g,
					translateRule:"Ća"
				}
			},
	Letter_ts:{
				rule1:{
					reg:/ц/g,
					translateRule:"c"
				},
				rule2:{
					reg:/ць/g,
					translateRule:"ć"
				},
				rule3:{
					reg:/цє/g,
					translateRule:"će"
				},
				rule4:{
					reg:/цю/g,
					translateRule:"ću"
				},
				rule5:{
					reg:/ця/g,
					translateRule:"ća"
				}
			},
	Letter_Ch:{
				reg:/Ч/g,
				translateRule:"Č"
			},
	Letter_ch:{
				reg:/ч/g,
				translateRule:"č"
			},
	Letter_Sh:{
				reg:/Ш/g,
				translateRule:"Š"
			},
	Letter_sh:{
				reg:/ш/g,
				translateRule:"š"
			},
	Letter_Sch:{
				reg:/Щ/g,
				translateRule:"Šč"
			},
	Letter_sch:{
				reg:/щ/g,
				translateRule:"šč"
			},
	Letter_Yu:{
				reg:/Ю/g,
				translateRule:"Ju"
			},
	Letter_iu:{
				reg:/ю/g,
				translateRule:"ju"
			},
	Letter_Ya:{
				reg:/Я/g,
				translateRule:"Ya"
			},
	Letter_ia:{
				reg:/я/g,
				translateRule:"ja"
			},
	Letter_softMark:{
				reg:/ь/g,
				translateRule:""
			},
	Letter_apostrophe:{
				reg:/'/g,
				translateRule:"'"
			}
};